[workspace]
resolver = "2"
members = [ "line-index",
"parallel-hnsw",
"vectorlink",
"vectorlink-store",
"vectorlink-task", "vectorlink-task-monitor",
"vectorlink-worker"]

[profile.release]
debug = true
