[package]
name = "vectorlink-infra"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.2.0", features = ["behavior-version-latest"] }
aws-sdk-ec2 = "1.34.0"
tokio = { version = "1.37.0", features = ["full"] }
