[package]
name = "vectorlink-embed"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.5.0"
lazy_static = "1.4.0"
reqwest = "0.11.24"
serde = {version="1.0.196", features=["derive"]}
serde_json = "1.0.113"
thiserror = "1.0.56"
tiktoken-rs = "0.5.8"
tokio = "1.36.0"
